image: node:16.13.2

stages:
  - test
  - build

before_script:
  - npm install

test:
  stage: test
  tags:
    - linux
  cache:
    paths:
      - node_modules/
  script:
    - CI=true npm test

build:
  stage: build
  only:
  - master
  tags:
    - linux
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
    - build
    expire_in: 1 week
  steps:
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
