on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v1
      - run: sudo npm install -g yarn
      - run: yarn
      - run: yarn run build
      - run: yarn test