image: node:16.13.2

jobs:
  - test
  - build

before_script:
- npm install

on:
  push:
    branches:
      - "master"

jobs:
  test:
    stage: test
    tags:
      - linux
    cache:
      paths:
        - node_modules/
    script:
      - CI=true npm test

  # build:
  #   steps:
  #     - uses: actions/checkout@v1
  #     - run: sudo npm install -g yarn
  #     - run: yarn
  #     - run: yarn run build
  #     - uses: jakejarvis/s3-sync-action@master
  #       with:
  #         args: --acl public-read --follow-symlinks --delete
  #       env:
  #         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}